name: Build Regeneration Crystal Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v4

      - name: Установить Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Установить Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: Собрать мод
        run: gradle build --stacktrace

      - name: Сохранить готовый JAR
        uses: actions/upload-artifact@v4
        with:
          name: regeneration-crystal-mod
          path: build/libs/*.jar
          if-no-files-found: error
